// GENERATED by packages/gw-data/scripts/import-heroes.ts — DO NOT EDIT.
// Single source of truth: the GWCA HeroID enum + data/heroes-overlay.json,
// the same pipeline that writes data/heroes.json. Regenerate with:
//   pnpm --filter @gw1-mcp/gw-data run import:heroes
#pragma once

namespace account_export {

// Indexed by GW::Constants::HeroID. Ids 28-35 are the mercenary hire slots
// (stable in the GWCA enum, absent from heroes.json by design); ids the
// enum may gain before the next regeneration render "Unknown".
constexpr const char* kHeroNames[] = {
    "None", // 0
    "Norgu", // 1
    "Goren", // 2
    "Tahlkora", // 3
    "Master of Whispers", // 4
    "Acolyte Jin", // 5
    "Koss", // 6
    "Dunkoro", // 7
    "Acolyte Sousuke", // 8
    "Melonni", // 9
    "Zhed Shadowhoof", // 10
    "General Morgahn", // 11
    "Margrid the Sly", // 12
    "Zenmai", // 13
    "Olias", // 14
    "Razah", // 15
    "M.O.X.", // 16
    "Keiran Thackeray", // 17
    "Jora", // 18
    "Pyre Fierceshot", // 19
    "Anton", // 20
    "Livia", // 21
    "Hayda", // 22
    "Kahmu", // 23
    "Gwen", // 24
    "Xandra", // 25
    "Vekk", // 26
    "Ogden Stonehealer", // 27
    "Merc1", // 28
    "Merc2", // 29
    "Merc3", // 30
    "Merc4", // 31
    "Merc5", // 32
    "Merc6", // 33
    "Merc7", // 34
    "Merc8", // 35
    "Miku", // 36
    "Zei Ri", // 37
    "Devona", // 38
    "Ghost of Althea", // 39
};

} // namespace account_export
